---
engines:
  metrics:
    enabled: true
    config:
      threshold: 30  # Maximum cyclomatic complexity - aligned with TEC governance standards
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - typescript
      threshold: 3  # Minimum duplicate lines to trigger warning
  eslint:
    enabled: true
  markdownlint:
    enabled: true

# Explicitly disable specific complexity checks that are controlled by design
# in the TEC ecosystem (e.g., sovereign agent execution patterns)
exclude_patterns:
  - message: "Function has too many parameters"
    paths:
      - "**/ai-agent/**"
  - message: "Cognitive Complexity"
    paths:
      - "**/ai-agent/**"
      - "**/lib/forensic-utils.js"

exclude_paths:
  - "node_modules/**"
  - "dist/**"
  - "build/**"
  - ".next/**"
  - "coverage/**"
  - "*.min.js"
  - "*.min.css"
  - "package-lock.json"
  - "prisma/migrations/**"
  - ".vercel/**"
  - "tests/**/*.test.js"
  - "tests/**/*.spec.js"
