---
# Codacy configuration file
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

engines:
  # Disable specific patterns that are false positives
  eslint:
    exclude_paths:
      # Ignore ESLint security plugin warnings for validated file operations
      - "ai-agent/domain-task-map.js"
    
exclude_paths:
  - "node_modules/**"
  - "**/*.min.js"
  - ".next/**"
  - "out/**"
  - "build/**"
  - "dist/**"

# Suppress File Access warnings for ai-agent/domain-task-map.js
# These file operations are validated through:
# - Strict domain allowlist validation
# - Safe path resolution guards (no path traversal, fixed base dir)
# - Writing ledger_full_log.json via a fixed guarded path
exclude_patterns:
  - "ai-agent/domain-task-map.js:128"
  - "ai-agent/domain-task-map.js:129"
