rules:
  - id: no-complex-functions
    description: Keep functions simple
    pattern: |
      def ${name}(${params}):
          ${body}
    condition: complexity > 10
    
  - id: use-comprehensions
    description: Prefer list comprehensions
    
python_version: "3.10"

github:
  request_review: author
  sourcery_branch: sourcery/main
  
refactor:
  skip_default_rules: false
  
clone_detection:
  min_lines: 5
  min_duplicates: 2
