/**
 * Authenticate With Pi Use Case - TEC Assistant Domain
 * Handles Pi Network authentication
 */

import { User, UserStatus, UserRole } from "../../entities/User";
import { IUserRepository } from "../../interfaces/repositories/IUserRepository";
import { IPiNetworkService } from "../../interfaces/services/IPiNetworkService";

export interface AuthenticateWithPiInput {
  accessToken: string;
}

export interface AuthenticateWithPiOutput {
  user: User;
  isNewUser: boolean;
}

export class AuthenticateWithPi {
  constructor(
    private userRepository: IUserRepository,
    private piNetworkService: IPiNetworkService,
  ) {}

  async execute(
    input: AuthenticateWithPiInput,
  ): Promise<AuthenticateWithPiOutput> {
    // Verify Pi authentication
    const piAuth = await this.piNetworkService.verifyAuth(input.accessToken);

    // Check if user exists
    let user = await this.userRepository.findByPiUid(piAuth.uid);
    let isNewUser = false;

    if (!user) {
      // Create new user
      user = new User({
        id: "", // Will be generated by repository
        piUid: piAuth.uid,
        piUsername: piAuth.username,
        walletAddress: piAuth.walletAddress,
        currentStreak: 0,
        longestStreak: 0,
        totalXp: 0,
        level: 1,
        status: UserStatus.ACTIVE,
        role: UserRole.USER,
        createdAt: new Date(),
        updatedAt: new Date(),
        lastActiveAt: new Date(),
      });

      user = await this.userRepository.create(user);
      isNewUser = true;
    } else {
      // Update last active
      user.updateLastActive();
      user = await this.userRepository.update(user);
    }

    return { user, isNewUser };
  }
}
