/**
 * Generate Daily Signal Use Case - TEC Assistant Domain
 * Generates a signal for a specific date (admin use)
 */

import { Signal, SignalType } from "../../entities/Signal";
import { ISignalRepository } from "../../interfaces/repositories/ISignalRepository";

export interface GenerateDailySignalInput {
  date: Date;
  signalType?: SignalType; // Optional override
}

export interface GenerateDailySignalOutput {
  signal: Signal;
}

export class GenerateDailySignal {
  constructor(private signalRepository: ISignalRepository) {}

  async execute(
    input: GenerateDailySignalInput,
  ): Promise<GenerateDailySignalOutput> {
    const date = this.getStartOfDay(input.date);

    // Check if signal already exists
    const existingSignal = await this.signalRepository.findByDate(date);
    if (existingSignal) {
      return { signal: existingSignal };
    }

    // Generate or use provided signal type
    const signalType = input.signalType || this.generateSignalType(date);

    const signal = new Signal({
      id: "", // Will be generated by repository
      date,
      type: signalType,
      generatedAt: new Date(),
    });

    const createdSignal = await this.signalRepository.create(signal);
    return { signal: createdSignal };
  }

  /**
   * Generate signal type based on date hash
   */
  private generateSignalType(date: Date): SignalType {
    const dateString = date.toISOString().split("T")[0];
    const hash = this.simpleHash(dateString);
    const mod = hash % 3;

    switch (mod) {
      case 0:
        return SignalType.POSITIVE;
      case 1:
        return SignalType.NEUTRAL;
      case 2:
        return SignalType.CAUTION;
      default:
        return SignalType.NEUTRAL;
    }
  }

  /**
   * Simple hash function for deterministic signal generation
   */
  private simpleHash(str: string): number {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      const char = str.charCodeAt(i);
      hash = (hash << 5) - hash + char;
      hash = hash & hash;
    }
    return Math.abs(hash);
  }

  /**
   * Get start of day (midnight)
   */
  private getStartOfDay(date: Date): Date {
    const newDate = new Date(date);
    newDate.setHours(0, 0, 0, 0);
    return newDate;
  }
}
