/**
 * Get Today Signal Use Case - TEC Assistant Domain
 * Retrieves or generates today's daily signal
 */

import { Signal, SignalType } from "../../entities/Signal";
import { ISignalRepository } from "../../interfaces/repositories/ISignalRepository";

export interface GetTodaySignalOutput {
  signal: Signal;
}

export class GetTodaySignal {
  constructor(private signalRepository: ISignalRepository) {}

  async execute(): Promise<GetTodaySignalOutput> {
    const today = this.getStartOfDay(new Date());

    // Try to get existing signal
    let signal = await this.signalRepository.findByDate(today);

    if (!signal) {
      // Generate new signal if not found
      const signalType = this.generateSignalType(today);
      signal = new Signal({
        id: "", // Will be generated by repository
        date: today,
        type: signalType,
        generatedAt: new Date(),
      });

      signal = await this.signalRepository.create(signal);
    }

    return { signal };
  }

  /**
   * Generate signal type based on date hash
   * Algorithm: hash(date) % 3 -> POSITIVE/NEUTRAL/CAUTION
   */
  private generateSignalType(date: Date): SignalType {
    const dateString = date.toISOString().split("T")[0];
    const hash = this.simpleHash(dateString);
    const mod = hash % 3;

    switch (mod) {
      case 0:
        return SignalType.POSITIVE;
      case 1:
        return SignalType.NEUTRAL;
      case 2:
        return SignalType.CAUTION;
      default:
        return SignalType.NEUTRAL;
    }
  }

  /**
   * Simple hash function for deterministic signal generation
   */
  private simpleHash(str: string): number {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      const char = str.charCodeAt(i);
      hash = (hash << 5) - hash + char;
      hash = hash & hash; // Convert to 32-bit integer
    }
    return Math.abs(hash);
  }

  /**
   * Get start of day (midnight)
   */
  private getStartOfDay(date: Date): Date {
    const newDate = new Date(date);
    newDate.setHours(0, 0, 0, 0);
    return newDate;
  }
}
