/**
 * Unlock Feature Use Case - TEC Assistant Domain
 * Handles feature unlock with Pi payment
 */

import { Unlock } from "../../entities/Unlock";
import {
  Transaction,
  TransactionType,
  TransactionStatus,
} from "../../entities/Transaction";
import { IUnlockRepository } from "../../interfaces/repositories/IUnlockRepository";
import { ITransactionRepository } from "../../interfaces/repositories/ITransactionRepository";
import { IPiNetworkService } from "../../interfaces/services/IPiNetworkService";

export interface UnlockFeatureInput {
  userId: string;
  featureKey: string;
  amount: number;
  expiresAt?: Date;
}

export interface UnlockFeatureOutput {
  unlock: Unlock;
  transaction: Transaction;
  piPaymentId: string;
}

export class UnlockFeature {
  constructor(
    private unlockRepository: IUnlockRepository,
    private transactionRepository: ITransactionRepository,
    private piNetworkService: IPiNetworkService,
  ) {}

  async execute(input: UnlockFeatureInput): Promise<UnlockFeatureOutput> {
    // Check if already unlocked
    const existingUnlock = await this.unlockRepository.findByUserAndFeature(
      input.userId,
      input.featureKey,
    );

    if (existingUnlock && existingUnlock.isValid()) {
      throw new Error("Feature already unlocked");
    }

    // Create Pi payment
    const piPaymentId = await this.piNetworkService.createPayment({
      identifier: `unlock_${input.featureKey}_${Date.now()}`,
      amount: input.amount,
      memo: `Unlock feature: ${input.featureKey}`,
      metadata: {
        userId: input.userId,
        featureKey: input.featureKey,
      },
    });

    // Create transaction record
    const transaction = new Transaction({
      id: "", // Will be generated by repository
      userId: input.userId,
      piPaymentId,
      amount: input.amount,
      type: TransactionType.UNLOCK_FEATURE,
      status: TransactionStatus.PENDING,
      itemId: input.featureKey,
      metadata: {
        featureKey: input.featureKey,
      },
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    const createdTransaction =
      await this.transactionRepository.create(transaction);

    // Create unlock record (pending payment completion)
    const unlock = new Unlock({
      id: "", // Will be generated by repository
      userId: input.userId,
      featureKey: input.featureKey,
      transactionId: createdTransaction.id,
      unlockedAt: new Date(),
      expiresAt: input.expiresAt,
    });

    const createdUnlock = await this.unlockRepository.create(unlock);

    return {
      unlock: createdUnlock,
      transaction: createdTransaction,
      piPaymentId,
    };
  }
}
