#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run commitlint only if a configuration file is present
if [ -f "commitlint.config.js" ] || [ -f ".commitlintrc.json" ]; then
  npx --no -- commitlint --edit "$1"
fi
